name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  ### [Version Log](https://github.com/theajack/disable-devtool/blob/master/helper/version.en.md)

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  # - title: 'Breaking'
  #   label: 'type: feat'x
  - title: 'New'
    label: 'type: feat'
  - title: 'Bug Fixes'
    label: 'type: fix'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Other changes'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'type: feat'
  # minor:
  #   labels:
  #     - 'type: feat'
  patch:
    labels:
      - 'type: fix'
      - 'type: docs'

exclude-labels:
  - 'skip-changelog'
